server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
  data:
    redis:
      host:
      port:
      password:  # 如果有密码
      database: 0
      timeout: 5000
      username: default
      lettuce:
        pool:
          max-idle: 16
          max-active: 32
          min-idle: 8

  servlet:
    multipart:
      max-file-size: 500MB       # 单个文件最大 100MB
      max-request-size: 500MB    # 单次请求最大 100MB
  mvc:
    async:
      request-timeout:
# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml  # XML映射文件位置
  type-aliases-package: cn.civer.blog.Model.Entity  # 实体类包路径
  configuration:
    map-underscore-to-camel-case: true  # 自动下划线转驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 日志输出
jwt:
  secret: jwtkey1111111111111111111111111111111111111
  expiration-ms: 86400000 # 24 hours

# 异步线程池 配置
async:
  pool:
    core-size: 4
    max-size: 8
    queue-capacity: 100
# 华为云OBS
huawei:
  obs:
    endpoint: # 端点
    accessKey:
    secretAccessKey:
    bucketName:
    expiration:
    accessUrl: # 自定义域名 或 桶名.端点
